AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  diplom-sam-app

  Sample SAM Template for diplom-sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: shardId
          AttributeType: S
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: shardId
          KeyType: HASH
        - AttributeName: orderId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: OrderTable

  GetOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/OrderService
      Handler: handlers.getOrderHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /order/{id}
            Method: get
      Environment:
        Variables:
          ORDER_TABLE_NAME: OrderTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: OrderTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  DeleteOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/OrderService
      Handler: handlers.deleteOrderHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /order/{id}
            Method: delete
      Environment:
        Variables:
          ORDER_TABLE_NAME: OrderTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: OrderTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  UpdateOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/OrderService
      Handler: handlers.updateOrderHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /order/{id}
            Method: put
      Environment:
        Variables:
          ORDER_TABLE_NAME: OrderTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: OrderTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  CreateOrder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/OrderService
      Handler: handlers.createOrderHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /order
            Method: post
      Environment:
        Variables:
          ORDER_TABLE_NAME: OrderTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: OrderTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  GetAllOrders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/OrderService
      Handler: handlers.getAllOrdersHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /orders
            Method: get
      Environment:
        Variables:
          ORDER_TABLE_NAME: OrderTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: OrderTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: shardId
          AttributeType: S
        - AttributeName: productId
          AttributeType: S
      KeySchema:
        - AttributeName: shardId
          KeyType: HASH
        - AttributeName: productId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: ProductTable

  GetProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ProductService
      Handler: handlers.getProductHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /product/{id}
            Method: get
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: ProductTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: ProductTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  DeleteProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ProductService
      Handler: handlers.deleteProductHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /product/{id}
            Method: delete
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: ProductTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ProductTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  UpdateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ProductService
      Handler: handlers.updateProductHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /product/{id}
            Method: put
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: ProductTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ProductTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  CreateProduct:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ProductService
      Handler: handlers.createProductHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /product
            Method: post
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: ProductTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ProductTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  GetAllProductss:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ProductService
      Handler: handlers.getAllProductsHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetOrder:
          Type: Api
          Properties:
            Path: /products
            Method: get
      Environment:
        Variables:
          PRODUCT_TABLE_NAME: ProductTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ProductTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handlers.ts

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  ApiGatewayEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order/{id}"
  GetOrderFunctionArn:
    Description: ARN for GetOrder Lambda Function
    Value: !GetAtt GetOrder.Arn
  OrderTableArn:
    Description: ARN for Order DynamoDB Table
    Value: !GetAtt OrderTable.Arn
